language: node_js

node_js:
  - "8.8.1"

script:
  - npm test
  
cache:
 - npm install

env:
- NODE_ENV=test

after_success:
   - npm run coverage
   - npm run cover

services:
  - postgresql

before_script:
  - psql -c 'create database testDb;' -U postgres