language: node_js

node_js:
  - "stable"

services:
  - postgresql

install:
 - npm install

env:
- NODE_ENV=test

cache:
  directories:
  - "node_modules"

before_script:
  - createuser events -s -U postgres
  - createdb testDb --username=postgres
  - sequelize db:migrate

script:
  - npm test