language: node_js

node_js:
  - "8.8.1"

script:
  - npm test
  
cache:
 - npm install

after_success:
   - npm run coverage
   - npm run cover

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres