language: node_js

node_js:
  - "stable"

services:
  - postgresql

install:
 - npm install

env:
- NODE_ENV=test

cache:
  directories:
  - "node_modules"

before_script:
- psql -c 'create database testDb;' -U postgres

script:
  - npm test