language: node_js

node_js:
  - "stable"

services:
  - postgresql

install:
 - npm install

env:
- NODE_ENV=test

before_script:
- createdb testDb --username=postgres
- sequelize db:migrate

script:
  - npm test

cache:
  directories:
  - "node_modules"